import { Bus, Clock3, MapPin, TrainFront } from "lucide-react";
import { FestivalLayout } from "@/components/FestivalLayout";

export default function Info() {
  return <FestivalLayout>
    <section className="page-hero"><div className="container"><span className="eyebrow">Chega junto</span><h1 className="display">Tudo pra você<br />chegar de boa</h1><p>Informações pra curtir o Pagode do Capão sem correrias: endereço, transporte, horários e os combinados da nossa roda.</p></div></section>
    <section className="section section-cream"><div className="container"><div className="info-grid"><div className="info-card"><span className="eyebrow">Onde acontece</span><h2>Fábrica de Cultura Capão</h2><ul className="location-list"><li><MapPin size={19}/><div><strong>Endereço</strong><span>Av. Inácio Dias da Silva, 1140<br />Capão Redondo · São Paulo · SP</span></div></li><li><Clock3 size={19}/><div><strong>Portões</strong><span>16h às 23h59 nos dois dias.<br />Chegue cedo e entre na roda.</span></div></li><li><TrainFront size={19}/><div><strong>Metrô mais próximo</strong><span>Capão Redondo · Linha 5-Lilás.<br />Depois, 12 min de ônibus.</span></div></li><li><Bus size={19}/><div><strong>Ônibus</strong><span>Consulte a linha mais conveniente no dia do evento.</span></div></li></ul></div><div className="map-wrap"><div className="map-visual" role="img" aria-label="Mapa ilustrativo da região do Capão Redondo, com a Fábrica de Cultura Capão e o Metrô Capão Redondo"><div className="map-street street-one"></div><div className="map-street street-two"></div><div className="map-street street-three"></div><span className="map-label label-a">Av. Inácio Dias<br />da Silva</span><span className="map-label label-b">Estrada de<br />Itapecerica</span><span className="map-label metro"><TrainFront size={14}/> Metrô Capão<br />Redondo</span><span className="map-pin"><MapPin size={25} fill="currentColor"/><strong>Fábrica de<br />Cultura Capão</strong></span><a className="map-link" href="https://www.google.com/maps/search/?api=1&query=F%C3%A1brica+de+Cultura+Cap%C3%A3o+Redondo" target="_blank" rel="noreferrer">Abrir rota no Maps ↗</a></div></div></div>
      <div className="rules"><article className="rule-card can"><h3>Pode trazer</h3><ul><li>Documento com foto e ingresso.</li><li>Garrafa plástica vazia para reabastecer.</li><li>Canga para sentar nas áreas liberadas.</li><li>Protetor solar e sua melhor energia.</li></ul></article><article className="rule-card cant"><h3>Melhor deixar em casa</h3><ul><li>Garrafas de vidro ou objetos cortantes.</li><li>Bebidas e comidas de fora.</li><li>Caixas de som e instrumentos particulares.</li><li>Itens ilícitos ou que coloquem alguém em risco.</li></ul></article></div>
    </div></section>
  </FestivalLayout>;
}
